"""Generate the runtime food dataset from the source workbook, without dependencies."""
import argparse
import json
from pathlib import Path
import posixpath
import zipfile
import xml.etree.ElementTree as ET

WEB = Path(__file__).resolve().parents[1]
NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
REL = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
HEADERS = ["Category", "Food", "Phase", "General", "Halal", "Vegetarian", "Vegan", "Notes & sources"]
PHASES = {"Both", "Low-residue days", "Clear-liquid day"}
STATUSES = {"Allowed", "Avoid", "Check hospital", "Check label"}


def read_foods(path):
    with zipfile.ZipFile(path) as book:
        workbook = ET.fromstring(book.read("xl/workbook.xml"))
        sheet = next(s for s in workbook.findall("m:sheets/m:sheet", NS) if s.get("name") == "Food Guide")
        relations = ET.fromstring(book.read("xl/_rels/workbook.xml.rels"))
        target = next(r.get("Target") for r in relations if r.get("Id") == sheet.get(f"{{{REL}}}id"))
        sheet_path = target.lstrip("/") if target.startswith("/") else posixpath.normpath(posixpath.join("xl", target))
        strings = []
        if "xl/sharedStrings.xml" in book.namelist():
            strings = ["".join(s.itertext()) for s in ET.fromstring(book.read("xl/sharedStrings.xml")).findall("m:si", NS)]
        rows = []
        for row in ET.fromstring(book.read(sheet_path)).findall("m:sheetData/m:row", NS):
            cells = {}
            for cell in row.findall("m:c", NS):
                value = cell.find("m:v", NS)
                value = value.text if value is not None else ""
                if cell.get("t") == "s":
                    value = strings[int(value)]
                elif cell.get("t") == "inlineStr":
                    inline = cell.find("m:is", NS)
                    value = "".join(inline.itertext()) if inline is not None else ""
                cells[cell.get("r").rstrip("0123456789")] = value or ""
            if any(cells.values()):
                rows.append((int(row.get("r")), [cells.get(c, "") for c in "ABCDEFGH"]))
        if not rows or rows[0][1] != HEADERS:
            raise ValueError("Food Guide columns do not match the expected headers")
        foods = []
        for number, values in rows[1:]:
            category, food, phase, general, halal, vegetarian, vegan, notes = values
            if not category or not food or phase not in PHASES or any(s not in STATUSES for s in [general, halal, vegetarian, vegan]):
                raise ValueError(f"Invalid food, category, phase or status at row {number}")
            foods.append(dict(id=f"food-{number}", sourceRow=number, category=category, food=food, phase=phase,
                              statuses=dict(General=general, Vegetarian=vegetarian, Vegan=vegan), notes=notes))
        return foods


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=WEB.parent / "colonoscopy_diet_food_guide.xlsx")
    parser.add_argument("--check", action="store_true", help="Verify the dataset without changing it")
    args = parser.parse_args()
    foods = read_foods(args.source)
    content = "// Generated by scripts/import-diet.py from Food Guide. Runtime does not read Excel.\n"
    content += "import type { FoodRecord } from './diet.ts'\n\n"
    content += "export const DIET_FOODS: readonly FoodRecord[] = " + json.dumps(foods, ensure_ascii=False, indent=2) + "\n"
    destination = WEB / "src/domain/diet-foods.ts"
    if args.check:
        if destination.read_text() != content:
            raise SystemExit("Diet dataset differs from the workbook. Run npm run import:diet.")
    else:
        destination.write_text(content)
    print(f"{'Verified' if args.check else 'Imported'} {len(foods)} foods in {len(set(f['category'] for f in foods))} categories.")


if __name__ == "__main__":
    main()
