// Generated by scripts/import-diet.py from Food Guide. Runtime does not read Excel.
import type { FoodRecord } from './diet.ts'

export const DIET_FOODS: readonly FoodRecord[] = [
  {
    "id": "food-2",
    "sourceRow": 2,
    "category": "Grains & starches",
    "food": "White rice",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": ""
  },
  {
    "id": "food-3",
    "sourceRow": 3,
    "category": "Grains & starches",
    "food": "White porridge / congee (plain)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Plain only. Not cooked in meat/fish stock for vegetarian/vegan; no toppings with veg, seeds or coconut."
  },
  {
    "id": "food-4",
    "sourceRow": 4,
    "category": "Grains & starches",
    "food": "White bread",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Check label"
    },
    "notes": "Vegan: many loaves contain milk, egg or butter. Halal: lard is rare but check the label."
  },
  {
    "id": "food-5",
    "sourceRow": 5,
    "category": "Grains & starches",
    "food": "Plain biscuits (refined, no wholegrain)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Check label"
    },
    "notes": "Halal: check for lard/gelatin. Vegan: check for milk/butter."
  },
  {
    "id": "food-6",
    "sourceRow": 6,
    "category": "Grains & starches",
    "food": "Bee hoon (rice vermicelli)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Served plain. Remove vegetables and garnishes."
  },
  {
    "id": "food-7",
    "sourceRow": 7,
    "category": "Grains & starches",
    "food": "Kway teow (flat rice noodles)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Served plain. Remove vegetables, beansprouts and chilli."
  },
  {
    "id": "food-8",
    "sourceRow": 8,
    "category": "Grains & starches",
    "food": "Yellow noodles",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Check label"
    },
    "notes": "Vegan: often contains egg. Team confirmed refined noodles are fine."
  },
  {
    "id": "food-9",
    "sourceRow": 9,
    "category": "Grains & starches",
    "food": "Mee pok / mee kia (egg noodles)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Check label"
    },
    "notes": "Vegan: egg noodles are not vegan; mee kia is sometimes egg-free, check the label."
  },
  {
    "id": "food-10",
    "sourceRow": 10,
    "category": "Grains & starches",
    "food": "Egg noodles",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Avoid"
    },
    "notes": "SCS list allows. Not vegan (contains egg)."
  },
  {
    "id": "food-11",
    "sourceRow": 11,
    "category": "Grains & starches",
    "food": "Mee sua",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Team confirmed refined noodles are fine."
  },
  {
    "id": "food-12",
    "sourceRow": 12,
    "category": "Grains & starches",
    "food": "Refined pasta",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Check label"
    },
    "notes": "Vegan: dried pasta is usually egg-free, fresh pasta often has egg."
  },
  {
    "id": "food-13",
    "sourceRow": 13,
    "category": "Grains & starches",
    "food": "Idli",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Plain, without vegetable or coconut chutney with seeds."
  },
  {
    "id": "food-14",
    "sourceRow": 14,
    "category": "Grains & starches",
    "food": "Thosai (plain)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Plain only; no potato-veg masala filling."
  },
  {
    "id": "food-15",
    "sourceRow": 15,
    "category": "Grains & starches",
    "food": "Iddiyappam / putu mayam",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Without grated coconut topping."
  },
  {
    "id": "food-16",
    "sourceRow": 16,
    "category": "Grains & starches",
    "food": "Plain cornflakes / rice cereal",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "No fruit, nuts, seeds or wholegrain. Eat with milk (low-residue days) or strained soy milk."
  },
  {
    "id": "food-17",
    "sourceRow": 17,
    "category": "Grains & starches",
    "food": "Potato (peeled, well-cooked)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Peeled potato allowed per Parkway East and the team. SCS strict list allows no vegetables."
  },
  {
    "id": "food-18",
    "sourceRow": 18,
    "category": "Grains & starches",
    "food": "Sweet potato / yam (peeled, well-cooked)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Check hospital"
    },
    "notes": "Team: usually allowed, some clinics stricter. Not on SCS or Parkway East lists."
  },
  {
    "id": "food-19",
    "sourceRow": 19,
    "category": "Grains & starches",
    "food": "Brown / red rice",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-20",
    "sourceRow": 20,
    "category": "Grains & starches",
    "food": "Wholemeal / wholegrain bread and biscuits",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-21",
    "sourceRow": 21,
    "category": "Grains & starches",
    "food": "Chapati, wholemeal naan",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-22",
    "sourceRow": 22,
    "category": "Grains & starches",
    "food": "Vadai",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-23",
    "sourceRow": 23,
    "category": "Grains & starches",
    "food": "Oats, muesli, granola",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-24",
    "sourceRow": 24,
    "category": "Grains & starches",
    "food": "Quinoa, millet, bran",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-25",
    "sourceRow": 25,
    "category": "Grains & starches",
    "food": "Wholegrain / high-fibre / buckwheat noodles",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-26",
    "sourceRow": 26,
    "category": "Meat & protein",
    "food": "Fish",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Cook until soft, no bones."
  },
  {
    "id": "food-27",
    "sourceRow": 27,
    "category": "Meat & protein",
    "food": "Chicken",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Halal: halal-certified only. Small, well-cooked, tender pieces; no skin/gristle."
  },
  {
    "id": "food-28",
    "sourceRow": 28,
    "category": "Meat & protein",
    "food": "Pork",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "SCS list allows."
  },
  {
    "id": "food-29",
    "sourceRow": 29,
    "category": "Meat & protein",
    "food": "Tender lean meat (well-cooked, cut small)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Halal: halal-certified only. Team: avoid tough cuts with ligaments or connective tissue."
  },
  {
    "id": "food-30",
    "sourceRow": 30,
    "category": "Meat & protein",
    "food": "Eggs",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Avoid"
    },
    "notes": "Vegetarian: fine for lacto-ovo. Many Indian-vegetarian and Buddhist vegetarians avoid eggs, so ask the patient."
  },
  {
    "id": "food-31",
    "sourceRow": 31,
    "category": "Meat & protein",
    "food": "Prawns / shellfish",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Halal: generally accepted in Singapore (Shafi'i), confirm for the individual patient. Parkway East: cockles not suitable."
  },
  {
    "id": "food-32",
    "sourceRow": 32,
    "category": "Meat & protein",
    "food": "Tofu (plain)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": ""
  },
  {
    "id": "food-33",
    "sourceRow": 33,
    "category": "Meat & protein",
    "food": "Taukwa (plain)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": ""
  },
  {
    "id": "food-34",
    "sourceRow": 34,
    "category": "Meat & protein",
    "food": "Tau pok (plain)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Team: fine if plain. Not the ones stuffed with vegetables."
  },
  {
    "id": "food-35",
    "sourceRow": 35,
    "category": "Meat & protein",
    "food": "Vegetarian mock meat",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Check label"
    },
    "notes": "Halal: needs halal certification. Vegan: check for egg white/milk. Must not contain mushroom or veg pieces."
  },
  {
    "id": "food-36",
    "sourceRow": 36,
    "category": "Meat & protein",
    "food": "Plant protein powder",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "SCS. Choose one without added fibre, fruit or nut pieces."
  },
  {
    "id": "food-37",
    "sourceRow": 37,
    "category": "Meat & protein",
    "food": "Nutrition supplements (when needed)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Check label"
    },
    "notes": "Parkway East. Halal/vegan: many contain milk/gelatin, check the label."
  },
  {
    "id": "food-38",
    "sourceRow": 38,
    "category": "Meat & protein",
    "food": "Smooth nut butter (thin layer, no chunks)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Team only. Thin layer."
  },
  {
    "id": "food-39",
    "sourceRow": 39,
    "category": "Meat & protein",
    "food": "Fishballs / fishcake / luncheon meat",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Team: no extra residue if no veg/seeds added, but not a healthy choice. Halal: luncheon meat is often pork. Fishcake may contain veg pieces."
  },
  {
    "id": "food-40",
    "sourceRow": 40,
    "category": "Meat & protein",
    "food": "Beef / mutton (red meat)",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "SCS list: avoid. Team's answer on beef/mutton was unclear, confirm with hospital."
  },
  {
    "id": "food-41",
    "sourceRow": 41,
    "category": "Meat & protein",
    "food": "Tough / deep-fried meat",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-42",
    "sourceRow": 42,
    "category": "Meat & protein",
    "food": "Sausage, lap cheong, salami (processed meat)",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "SCS list: avoid."
  },
  {
    "id": "food-43",
    "sourceRow": 43,
    "category": "Meat & protein",
    "food": "Tempeh",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-44",
    "sourceRow": 44,
    "category": "Meat & protein",
    "food": "Beans, lentils, dal",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-45",
    "sourceRow": 45,
    "category": "Meat & protein",
    "food": "Nuts and seeds (whole/chunky)",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-46",
    "sourceRow": 46,
    "category": "Meat & protein",
    "food": "Tau pok / tofu stuffed with vegetables",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-47",
    "sourceRow": 47,
    "category": "Dairy & alternatives",
    "food": "Milk",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Avoid"
    },
    "notes": "SCS: follow institution. Parkway East: low-fat/skimmed, controlled portions. Team: yes. SKH: avoid dairy. Not on the clear-liquid day."
  },
  {
    "id": "food-48",
    "sourceRow": 48,
    "category": "Dairy & alternatives",
    "food": "Cheese (plain)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Avoid"
    },
    "notes": "Parkway East: low-fat, controlled portions. SKH: avoid. Halal/vegetarian: check for animal rennet."
  },
  {
    "id": "food-49",
    "sourceRow": 49,
    "category": "Dairy & alternatives",
    "food": "Plain yoghurt",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Avoid"
    },
    "notes": "Parkway East: low-fat, controlled portions. SKH: avoid. Halal/vegetarian: some contain gelatin. No fruit or nuts."
  },
  {
    "id": "food-50",
    "sourceRow": 50,
    "category": "Dairy & alternatives",
    "food": "Ice cream (plain)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Avoid"
    },
    "notes": "SCS list allows (hospital-dependent). Halal/vegetarian: check for gelatin."
  },
  {
    "id": "food-51",
    "sourceRow": 51,
    "category": "Dairy & alternatives",
    "food": "Custard",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Avoid"
    },
    "notes": "SCS list allows (hospital-dependent). Contains milk and egg."
  },
  {
    "id": "food-52",
    "sourceRow": 52,
    "category": "Dairy & alternatives",
    "food": "Condensed milk / evaporated milk / cream",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Avoid"
    },
    "notes": "Team: no restriction if no nuts/seeds/veg/fruit added. Follow hospital dairy rule."
  },
  {
    "id": "food-53",
    "sourceRow": 53,
    "category": "Dairy & alternatives",
    "food": "Milo",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Avoid"
    },
    "notes": "SCS and Parkway East: yes. Stop on the clear-liquid day. Contains milk."
  },
  {
    "id": "food-54",
    "sourceRow": 54,
    "category": "Dairy & alternatives",
    "food": "Horlicks",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Avoid"
    },
    "notes": "Team: stop on the clear-liquid day. Contains milk."
  },
  {
    "id": "food-55",
    "sourceRow": 55,
    "category": "Dairy & alternatives",
    "food": "Kopi / teh with milk (kopi-C, teh-C, teh tarik)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Avoid"
    },
    "notes": "Team: stop on the clear-liquid day."
  },
  {
    "id": "food-56",
    "sourceRow": 56,
    "category": "Dairy & alternatives",
    "food": "Soy milk (strained)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "SCS and team: yes on low-residue days, not on the clear-liquid day."
  },
  {
    "id": "food-57",
    "sourceRow": 57,
    "category": "Dairy & alternatives",
    "food": "Coconut milk",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Check hospital"
    },
    "notes": "Team: yes. Parkway East: laksa unsuitable because of coconut milk. SCS fruit list: avoid coconut."
  },
  {
    "id": "food-58",
    "sourceRow": 58,
    "category": "Dairy & alternatives",
    "food": "Flavoured / fruit / nut dairy",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "SCS list: avoid."
  },
  {
    "id": "food-59",
    "sourceRow": 59,
    "category": "Fruit & juice",
    "food": "Strained fruit juice, no pulp (apple, pear, grape)",
    "phase": "Both",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Choose light colour. Avoid red/purple/blue."
  },
  {
    "id": "food-60",
    "sourceRow": 60,
    "category": "Fruit & juice",
    "food": "Small ripe banana",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Check hospital"
    },
    "notes": "SCS: allowed. Parkway East: not allowed."
  },
  {
    "id": "food-61",
    "sourceRow": 61,
    "category": "Fruit & juice",
    "food": "Small avocado",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Check hospital"
    },
    "notes": "SCS: allowed. Parkway East: not allowed."
  },
  {
    "id": "food-62",
    "sourceRow": 62,
    "category": "Fruit & juice",
    "food": "Fruit with skin, seeds or pulp",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-63",
    "sourceRow": 63,
    "category": "Fruit & juice",
    "food": "Dried fruit",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-64",
    "sourceRow": 64,
    "category": "Fruit & juice",
    "food": "Coconut (flesh)",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-65",
    "sourceRow": 65,
    "category": "Fruit & juice",
    "food": "Prune juice",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Team: contains fibre."
  },
  {
    "id": "food-66",
    "sourceRow": 66,
    "category": "Fruit & juice",
    "food": "Orange, tomato, sugarcane, calamansi juice",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Team: may contain pulp or seeds."
  },
  {
    "id": "food-67",
    "sourceRow": 67,
    "category": "Vegetables",
    "food": "Strained vegetable soup / juice",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Check hospital"
    },
    "notes": "Parkway East: allowed. SCS strict version: no vegetables."
  },
  {
    "id": "food-68",
    "sourceRow": 68,
    "category": "Vegetables",
    "food": "Onion, garlic, ginger, lemongrass (flavouring, not visible)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Check hospital"
    },
    "notes": "Team: keep minimal; invisible amounts usually OK. Some Buddhist/Indian vegetarians avoid onion and garlic."
  },
  {
    "id": "food-69",
    "sourceRow": 69,
    "category": "Vegetables",
    "food": "Well-cooked peeled vegetables (small amounts)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Check hospital"
    },
    "notes": "SCS: only if patient wants and institution allows. Parkway East: no."
  },
  {
    "id": "food-70",
    "sourceRow": 70,
    "category": "Vegetables",
    "food": "All other vegetables (raw, with skin/seeds, corn, leafy greens)",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-71",
    "sourceRow": 71,
    "category": "Vegetables",
    "food": "Mushrooms",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Team: very high fibre."
  },
  {
    "id": "food-72",
    "sourceRow": 72,
    "category": "Snacks & desserts",
    "food": "Agar-agar / clear jelly (no fruit pieces)",
    "phase": "Both",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Not red, purple, blue or dark."
  },
  {
    "id": "food-73",
    "sourceRow": 73,
    "category": "Snacks & desserts",
    "food": "Gelatin jelly (clear, no fruit pieces)",
    "phase": "Both",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Halal: only if gelatin is halal-certified. Not red, purple, blue or dark."
  },
  {
    "id": "food-74",
    "sourceRow": 74,
    "category": "Snacks & desserts",
    "food": "Tau huay (soya bean curd)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Plain, with syrup only."
  },
  {
    "id": "food-75",
    "sourceRow": 75,
    "category": "Snacks & desserts",
    "food": "Strained dessert soup",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "SCS. No bits (no beans, seeds, nuts, fruit)."
  },
  {
    "id": "food-76",
    "sourceRow": 76,
    "category": "Snacks & desserts",
    "food": "Plain cake",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Avoid"
    },
    "notes": "Contains egg and butter/milk, so not vegan. No fruit, nuts, seeds or wholegrain."
  },
  {
    "id": "food-77",
    "sourceRow": 77,
    "category": "Snacks & desserts",
    "food": "Sorbet",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Check label"
    },
    "notes": "Vegan: some contain egg white. Not red/purple/blue."
  },
  {
    "id": "food-78",
    "sourceRow": 78,
    "category": "Snacks & desserts",
    "food": "Ice pops",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Check label",
      "Vegan": "Check label"
    },
    "notes": "Check for gelatin. Not red, purple or blue."
  },
  {
    "id": "food-79",
    "sourceRow": 79,
    "category": "Snacks & desserts",
    "food": "Plain sweets",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Check label",
      "Vegan": "Check label"
    },
    "notes": "Many contain gelatin. Not red, purple or blue."
  },
  {
    "id": "food-80",
    "sourceRow": 80,
    "category": "Snacks & desserts",
    "food": "Plain chocolate",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Check label"
    },
    "notes": "Vegan: choose dark chocolate without milk. No nuts, fruit or seeds."
  },
  {
    "id": "food-81",
    "sourceRow": 81,
    "category": "Snacks & desserts",
    "food": "Chwee kueh",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Check hospital",
      "Vegan": "Check hospital"
    },
    "notes": "SCS: yes. Parkway East: not suitable."
  },
  {
    "id": "food-82",
    "sourceRow": 82,
    "category": "Snacks & desserts",
    "food": "Desserts with fruit, nuts, seeds, wholegrain or coconut",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-83",
    "sourceRow": 83,
    "category": "Local dishes",
    "food": "Kaya toast (white bread)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Avoid"
    },
    "notes": "SCS and Parkway East: yes if white bread. Kaya contains egg and coconut milk, so not vegan."
  },
  {
    "id": "food-84",
    "sourceRow": 84,
    "category": "Local dishes",
    "food": "Mee soto (vegetables, beansprouts and garnish removed)",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Check hospital",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "SCS: avoid all veg. Parkway East: acceptable with modification. Chicken broth, so not vegetarian."
  },
  {
    "id": "food-85",
    "sourceRow": 85,
    "category": "Local dishes",
    "food": "Laksa",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Parkway East: coconut milk, cockles, beansprouts. SCS: avoid all veg."
  },
  {
    "id": "food-86",
    "sourceRow": 86,
    "category": "Sauces & condiments",
    "food": "Soy sauce / dark soy sauce",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Team: fine if no visible vegetable pieces."
  },
  {
    "id": "food-87",
    "sourceRow": 87,
    "category": "Sauces & condiments",
    "food": "Oyster sauce",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Team: fine if no visible veg pieces. Made from oysters."
  },
  {
    "id": "food-88",
    "sourceRow": 88,
    "category": "Sauces & condiments",
    "food": "Mayonnaise",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Avoid"
    },
    "notes": "Contains egg."
  },
  {
    "id": "food-89",
    "sourceRow": 89,
    "category": "Sauces & condiments",
    "food": "Ketchup",
    "phase": "Low-residue days",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "No visible veg pieces."
  },
  {
    "id": "food-90",
    "sourceRow": 90,
    "category": "Sauces & condiments",
    "food": "Chilli, sambal, chilli sauces",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Team: preferably avoid because of seeds/solids."
  },
  {
    "id": "food-91",
    "sourceRow": 91,
    "category": "Sauces & condiments",
    "food": "Garnishes: fried shallots, spring onion, coriander",
    "phase": "Both",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Team: remove."
  },
  {
    "id": "food-92",
    "sourceRow": 92,
    "category": "Clear liquids",
    "food": "Water",
    "phase": "Both",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": ""
  },
  {
    "id": "food-93",
    "sourceRow": 93,
    "category": "Clear liquids",
    "food": "Plain tea / black coffee (kopi-O, teh-O)",
    "phase": "Both",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "No milk on the clear-liquid day. Sugar is fine."
  },
  {
    "id": "food-94",
    "sourceRow": 94,
    "category": "Clear liquids",
    "food": "Isotonic / electrolyte drinks",
    "phase": "Clear-liquid day",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Team: prefer non-coloured versions. Not red, purple or blue."
  },
  {
    "id": "food-95",
    "sourceRow": 95,
    "category": "Clear liquids",
    "food": "Strained barley water",
    "phase": "Clear-liquid day",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Team: strained, diluted, not cloudy, no grains."
  },
  {
    "id": "food-96",
    "sourceRow": 96,
    "category": "Clear liquids",
    "food": "Clear broth, strained (chicken/meat)",
    "phase": "Clear-liquid day",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Halal: halal-certified source. No solids or oil bits."
  },
  {
    "id": "food-97",
    "sourceRow": 97,
    "category": "Clear liquids",
    "food": "Clear broth, strained (vegetable)",
    "phase": "Clear-liquid day",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Allowed"
    },
    "notes": "Fully strained, no solids."
  },
  {
    "id": "food-98",
    "sourceRow": 98,
    "category": "Clear liquids",
    "food": "Honey",
    "phase": "Clear-liquid day",
    "statuses": {
      "General": "Allowed",
      "Vegetarian": "Allowed",
      "Vegan": "Avoid"
    },
    "notes": "SCS. Many vegans avoid honey; use sugar or syrup."
  },
  {
    "id": "food-99",
    "sourceRow": 99,
    "category": "Clear liquids",
    "food": "Pulpy juice",
    "phase": "Clear-liquid day",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  },
  {
    "id": "food-100",
    "sourceRow": 100,
    "category": "Clear liquids",
    "food": "Milk, milky drinks (kopi, teh, Milo, Horlicks)",
    "phase": "Clear-liquid day",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Stop milk on the clear-liquid day."
  },
  {
    "id": "food-101",
    "sourceRow": 101,
    "category": "Clear liquids",
    "food": "Soy milk",
    "phase": "Clear-liquid day",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Team: fine on low-residue days but not on the clear-liquid day."
  },
  {
    "id": "food-102",
    "sourceRow": 102,
    "category": "Clear liquids",
    "food": "Red, purple, blue or dark coloured drinks/jelly",
    "phase": "Clear-liquid day",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": "Can look like blood during the scope."
  },
  {
    "id": "food-103",
    "sourceRow": 103,
    "category": "Clear liquids",
    "food": "Alcohol",
    "phase": "Clear-liquid day",
    "statuses": {
      "General": "Avoid",
      "Vegetarian": "Avoid",
      "Vegan": "Avoid"
    },
    "notes": ""
  }
]
